ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "priceMin" DECIMAL(12,2);
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "priceMax" DECIMAL(12,2);
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'TWD';
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "isAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;